apiVersion: v1
kind: Pod
metadata:
  namespace: abhishek-argoCD
  name: nginx-pod
  labels:
    app: myapp
spec:
  containers:
  - name: nginx-container
    image: nginx
    ports:
      - containerPort: 80
