apiVersion: v1
kind: Pod
metadata:
  namespace: abhishek-argocd
  name: nginx-pod
  labels:
    app: todo-app
spec:
  containers:
  - name: nginx-container
    image: nginx
    ports:
      - containerPort: 80
