apiVersion: v1
kind: Service
metadata: 
  namespace: nginx-argocd
  name: todo-service-nginx
spec:
  selector:
    app: todo-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80

  type: LoadBalancer    
